version: 2
updates:
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    rebase-strategy: "disabled"
